package dev.cxclear.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * M3 token 的数据结构与语义色门面。
 * 注意：M3Tokens 的 35 个字段名与 Theme.kt 里 toMaterialColorScheme 的 35 个具名参数逐一硬对应，增删字段必须同时改两处。
 */
data class M3Tokens(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val inversePrimary: Color,
    val surfaceDim: Color,
    val surfaceBright: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
)

data class AppColorTokens(
    val Surface0: Color,
    val Surface1: Color,
    val Surface2: Color,
    val Surface3: Color,
    val Surface4: Color,
    val Primary: Color,
    val PrimaryHover: Color,
    val PrimaryContainer: Color,
    val OnPrimary: Color,
    val Safe: Color,
    val Optional: Color,
    val Error: Color,
    val TextPrimary: Color,
    val TextSecondary: Color,
    val TextTertiary: Color,
    val Outline: Color,
    val OutlineVariant: Color,
    val TextOnScrim: Color,
    val Scrim: Color,
    val CategoryPackages: Color,
    val CategoryWorking: Color,
    val CategoryHistory: Color,
    val CategoryRetained: Color,
    val CylinderShellLight: Color,
    val CylinderShellMid: Color,
    val CylinderShellEdge: Color,
    /** 柱体高光 / 扫光混色用，暗色下不能硬写 White。 */
    val Highlight: Color,
)

internal fun appColorTokensOf(tokens: M3Tokens): AppColorTokens = AppColorTokens(
    Surface0 = tokens.surfaceContainerLowest,
    Surface1 = tokens.surface,
    Surface2 = tokens.surfaceContainer,
    Surface3 = tokens.surfaceContainerHighest,
    Surface4 = tokens.surfaceVariant,
    Primary = tokens.primary,
    PrimaryHover = tokens.inversePrimary,
    PrimaryContainer = tokens.primaryContainer,
    OnPrimary = tokens.onPrimary,
    Safe = tokens.primary,
    Optional = tokens.tertiary,
    Error = tokens.error,
    TextPrimary = tokens.onSurface,
    TextSecondary = tokens.onSurfaceVariant,
    TextTertiary = tokens.outline,
    Outline = tokens.outline,
    OutlineVariant = tokens.outlineVariant,
    TextOnScrim = tokens.inverseOnSurface,
    Scrim = tokens.scrim,
    CategoryPackages = tokens.inversePrimary,
    CategoryWorking = tokens.primary,
    CategoryHistory = tokens.onPrimaryContainer,
    CategoryRetained = tokens.inverseSurface,
    CylinderShellLight = tokens.surfaceContainerLowest,
    CylinderShellMid = tokens.surfaceContainerLow,
    CylinderShellEdge = tokens.surfaceContainerHigh,
    Highlight = tokens.surfaceBright,
)
